import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Router, { useRouter } from "next/router";
import { useEffect } from "react";
import About from "../components/About";
import Footer from "../components/Footer";
import Landing from "../components/Landing";
import Lens from "../components/Lens";
import Products from "../components/Products";

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-gray">
        <div className="w-[100%] ">
          {/* landing */}
          <Landing />
          {/* some lens  */}
          <Products products={products} />

          {/* About me  */}
          <About />

          {/* footer */}
          <Footer />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
export const getServerSideProps = async (context) => {
  const data = await axios.get(
    "https://pro-shop-swart.vercel.app/api/products"
  );
  const products = await data.data.products;
  const { search } = context.query;

  if (search) {
    const newProducts = products.filter((product) =>
      product.name.startsWith(search)
    );

    return {
      props: {
        products: newProducts,
      },
    };
  }
  return {
    props: {
      products: products,
    },
  };
};
